# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c9bc178db4a71e1475af9bb291fa0f91791518351742a124d9f3df6796233fc3ec6e5390d12a56c00b477fd8941cce891cf1682c0343a08253debae0e5e9378

test:
  secret_key_base: 514f68ec6b296b353bde5180a4c3677daa396131e4c9ce62fe8097a00028a1d3162275955db0a368c3bf84d70a64c1cbcb7c3f94980d9ad250f2def9b073ebea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
